# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: FOSSA scanning

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@12cd2235efa0937479335606d7c3ac9f6c0973b1  # v5.0.1

      - uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c  # v2.0.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          team: OpenTelemetry
